#!/usr/bin/lua
local cjson = require "cjson"
local function exec(cmd)
    local f = io.popen(cmd)
    if not f then return nil end
    local content = f:read("*all")
    f:close()
    return content
end
print("Content-type: application/json\n\n")
local out = exec("mmcli -L 2>/dev/null")
local out2 = exec("mmcli -m 0 -J 2>/dev/null")
print(cjson.encode({ mmcli_L = out, mmcli_m0 = out2 }))
