#!/usr/bin/lua
local cjson = require "cjson"
local function exec(cmd)
    local f = io.popen(cmd)
    if not f then return nil end
    local content = f:read("*all")
    f:close()
    return content
end
print("Content-type: application/json\n\n")
local ls = exec("ls -la /tmp 2>/dev/null")
local sms = exec("cat /tmp/modem_info 2>/dev/null")
print(cjson.encode({ ls = ls, modem_info = sms }))
