#!/usr/bin/lua
local cjson = require "cjson"
local function exec(cmd)
    local f = io.popen(cmd)
    if not f then return nil end
    local content = f:read("*all")
    f:close()
    return content
end
print("Content-type: application/json\n\n")
local out = exec("ubus -v list modem_ctrl 2>/dev/null")
local out2 = exec("ubus list 2>/dev/null")
print(cjson.encode({ modem_ctrl = out, all = out2 }))
