#!/usr/bin/lua
local cjson = require "cjson"
print("Content-type: application/json\n\n")

os.execute("/etc/init.d/sms_sync stop")
os.execute("killall sms_sync.lua 2>/dev/null")

local f = io.popen("/www/NTC_WRT/services/at_cmd.sh /dev/ttyUSB3 'AT+GTCCINFO?'")
local res = f:read("*a")
f:close()

print(cjson.encode({ at_res = res }))
